### ISSUE TITLE
Answering some TODOs I've seen

### ISSUE THREAD

**Issue by mvdan** [warpfork/smsh#2]
I've seen these scattered across the git repo, so I'll answer a few here.

> TODO it's not clear to me why this (ShellExitStatus) and ExitStatus are distinct

`exit 1` gives a `ShellExitStatus(1)` error, and `false` gives an `ExitStatus(1)` error. This is necessary so that `cmd/gosh` knows when to exit the shell or not.

> We already have that one TODO about statements vs granularity of the args

See https://github.com/warpfork/smsh/pull/1 for how I would have done it. I imagine you want to parse *one* statement per argument. At the moment the only way to do that is to parse the entire string and error manually if there are zero or multiple statements. I may add extra API for this, but I'm not sure.

> interp.Params("-e"), // TODO this doesn't do anything?
> interp.Params("-u"), // TODO check if this does either

I'm not sure - I did implement them and there are some tests, but I could have well missed some spots. Note that the former only affects whether `ExitStatus` or `ShellExitStatus` is returned, so you need to treat those errors differently. `-u` also makes unset variables error out with a `ShellExitStatus`.

> nodeStr := "todo:restring-the-cmd" // TODO this is hard to string back up!

Actually not hard. You have three options:

* If you want the original bytes, take the original string from `node.Pos().Offset` to `node.End().Offset`
* If you want the printed node (in the canonical format), use `syntax.Printer`
* If you want a dump to stdout to debug, use `syntax.DebugPrint`

**Comment by warpfork** [comment]
> exit 1 gives a ShellExitStatus(1) error, and false gives an ExitStatus(1) error. This is necessary so that cmd/gosh knows when to exit the shell or not.

Huh.  Okay :thinking:   I guess that... makes sense now.  :+1: 

> syntax.Printer

Oh nice.  I found the .Pos variant, but syntax.Printer is probably way more what I wanted.  Thanks for the pointer.

Semi-relatedly, I'm toying with the idea of trying to introduce another element of syntax so that the user could "tag" some statements, e.g. `"@frob: /bin/zat | cat -"` and then smsh could  use the "frob" string there in terse status reporting.  But the other half of me thinks that's a really complexity-adding bad idea and I should find some other totally different way to represent that.  Dunno.

> interp.Params("-e")

Yeah, I'm... please don't read my 5am comments as a deep or correct commentaries of your library :)  These were in fact very, very un-sober commits.  In other words, you can expand that "?" at the end of the comment there to read "Eric does not believe in self?!?  recheck latur".  (Trying to remember where my head was at: I think I only very belatedly realized that one of my other switches pretty much just dropped `interp.ExitStatus`, so... that... explains a lot.)

I suspect smsh is going to end up implementing something custom rather than "-e" mode anyway, because "-e" mode is one of the parts of bash that I most disagree with and want to shift the norms in smsh sequences.  But we'll see how that shakes out.

---

Thanks for the explains!

**Comment by frob** [comment]
While I like the idea of "terse status reporting" adding a feature like that to an interpreter could open it up to some serious injection attacks that would otherwise be avoided by simply not including the feature.

**Comment by mvdan** [comment]
> I'm toying with the idea of trying to introduce another element of syntax so that the user could "tag" some statements

I presume this is something that you'd do on your end, since it has little to do with shell syntax.

> Thanks for the explains!

I'm not great at writing documentation, so if anything else is confusing, feel free to ping me :)

**Comment by warpfork** [comment]
>  some serious injection attacks

I was confused until I saw your username and then I got the giggles :)  Sorry for pinging you with my code block escaping typo on the initial post :)

> I presume this is something that you'd do on your end, since it has little to do with shell syntax.

I think so, yes.  If it's a purely prefixed syntax thing, it can be implemented in the simplest possible way before handing off to your parser; no complex/interesting parser composition necessary.
